export const productos = {
    pasteles: [
        { nombre: "korean cakes", alergenos_comunes: "gluten, lácteos, huevo", otros_ingredientes: "azúcar, esencia de vainilla, queso crema, polvo para hornear", imagen: "../img/korean.webp" },
        { nombre: "mini de betabel", alergenos_comunes: "gluten, lácteos, huevo", otros_ingredientes: "azúcar, ralladura de betabel, cocoa en polvo, ganache de chocolate obscuro, polvo para hornear", imagen: "../img/betabel.webp" },
        { nombre: "con macarrons", alergenos_comunes: "gluten, lácteos, huevo, macarrons (harina de almendra), almendra fileteada", otros_ingredientes: "azúcar, mantequilla, esencia de vainilla, polvo para hornear", imagen: "../img/pastel-con-macarrons.webp" },
        { nombre: "avena con miel de agave", alergenos_comunes: "sin gluten, lácteos, miel de agave", otros_ingredientes: "harina de avena y huevo", imagen: "../img/avena-miel.webp" },
        { nombre: "chocolate sin gluten", alergenos_comunes: "sin gluten, lácteos, miel de agave", otros_ingredientes: "chocolate sin azúcar, miel de agave, polvo para hornear", imagen: "../img/chocolate-sin-gluten.webp" },
        { nombre: "ganache de chocolate", alergenos_comunes: "gluten, lácteos, huevo", otros_ingredientes: "azúcar, cacao en polvo, chocolate amargo, ganache de chocolate obscuro, polvo de hornear", imagen: "../img/ganache.webp" },
        { nombre: "ferrero", alergenos_comunes: "gluten, lácteos, huevo", otros_ingredientes: "azúcar, chocolate ferrero, nutella (a elección), trozos de avellana, polvo para hornear", imagen: "../img/ferrero.webp" },
        { nombre: "lavanda", alergenos_comunes: "gluten, lácteos, huevo", otros_ingredientes: "lavanda comestible, harina de trigo, polvo de hornear", imagen: "../img/lavanda.webp" },
        { nombre: "mascarpone", alergenos_comunes: "gluten, lácteos, huevo", otros_ingredientes: "azúcar, mantequilla, queso mascarpone, pasta de vainilla, polvo para hornear", imagen: "../img/mascarpone.webp" },
        { nombre: "tres leches", alergenos_comunes: "gluten, lácteos, huevo", otros_ingredientes: "azúcar, ron, esencia de vainilla", imagen: "../img/3-leches.webp" },
        { nombre: "zanahoria", alergenos_comunes: "gluten, lácteos, frutos secos, huevo", otros_ingredientes: "azúcar, canela, jengibre, polvo para hornear", imagen: "../img/zanahoria.webp" },
        { nombre: "fondant", alergenos_comunes: "gluten, lácteos, huevo", otros_ingredientes: "azúcar, esencia de vainilla, polvo para hornear", imagen: "../img/pastel-fondant.webp" },
        { nombre: "kitkat", alergenos_comunes: "gluten, lácteos, huevo, fresas", otros_ingredientes: "chocolate kitkat (dark, leche, blanco y rosa), cocoa, crema irlandesa, polvo para hornear", imagen: "../img/kitkat.webp" },
        { nombre: "conejito", alergenos_comunes: "gluten, lácteos, huevo", otros_ingredientes: "azúcar, chocolate turín de leche, polvo para hornear", imagen: "../img/conejito.webp" },
        { nombre: "red velvet", alergenos_comunes: "gluten, lácteos, huevo, colorante alimentario (rojo)", otros_ingredientes: "cocoa en polvo, mantequilla, polvo para hornear", imagen: "../img/red-velvet.webp" },
    ],
    galletas: [
        { nombre: "Quinoa", alergenos_comunes: "sin gluten, lácteos", otros_ingredientes: "quinoa, azúcar, mantequilla", imagen: "../img/quinoa.webp" },
        { nombre: "Pastisetas", alergenos_comunes: "gluten, lácteos", otros_ingredientes: "harina, azúcar glass, mantequilla", imagen: "../img/pastisetas.webp" },
        { nombre: "Cacahuate", alergenos_comunes: "sin gluten, frutos secos", otros_ingredientes: "cacahuate, mantequilla", imagen: "../img/cacahuate.webp" },
        { nombre: "Galletones", alergenos_comunes: "sin gluten, frutos secos", otros_ingredientes: "cacahuate, mantequilla", imagen: "../img/galletones.webp" },
        { nombre: "Royal Icing", alergenos_comunes: "sin gluten, lácteos", otros_ingredientes: "cacahuate, mantequilla", imagen: "../img/royalicing.webp" },
    ],
    tartas: [
        { nombre: "Tarta de mango", alergenos_comunes: "gluten, lácteos", otros_ingredientes: "harina, mango, mantequilla", imagen: "../img/mango.jpg" },
        { nombre: "Tarta de blueberry", alergenos_comunes: "gluten, lácteos", otros_ingredientes: "harina, blueberry, mantequilla", imagen: "../img/tarta-blueberry.webp" },
        { nombre: "Tarta de frutos", alergenos_comunes: "gluten, lácteos", otros_ingredientes: "harina, frutos mixtos, mantequilla", imagen: "../img/tarta-frutos.jpg" },
        { nombre: "Tarta de calabaza", alergenos_comunes: "gluten, lácteos", otros_ingredientes: "harina, calabaza, mantequilla", imagen: "../img/tarta-calabaza.webp" },
        { nombre: "Tarta de higo", alergenos_comunes: "gluten, lácteos", otros_ingredientes: "harina, higo, mantequilla", imagen: "../img/tarta-higo.webp" },
        { nombre: "Tarta de limón", alergenos_comunes: "gluten, lácteos", otros_ingredientes: "harina, limón, mantequilla", imagen: "../img/tarta-limon.jpg" },
        { nombre: "Tarta de frutos rojos", alergenos_comunes: "gluten, lácteos", otros_ingredientes: "harina, frutos rojos, mantequilla", imagen: "../img/tarta-frutos-rojos.webp" },
        { nombre: "Tarta de zarzamora", alergenos_comunes: "gluten, lácteos", otros_ingredientes: "harina, zarzamora, mantequilla", imagen: "../img/tarta-zarzamora.jpg" },
        { nombre: "Tarta de maracuyá", alergenos_comunes: "gluten, lácteos", otros_ingredientes: "harina, maracuyá, mantequilla", imagen: "../img/tarta-maracuya.webp" },
        { nombre: "Tarta de chocolate", alergenos_comunes: "gluten, lácteos", otros_ingredientes: "harina, chocolate, mantequilla", imagen: "../img/tarta-chocolate.webp" },
        { nombre: "Tarta de avellana", alergenos_comunes: "gluten, lácteos, frutos secos", otros_ingredientes: "harina, avellana, mantequilla", imagen: "../img/tarta-avellana.jpg" },
        { nombre: "Tarta de frambuesas", alergenos_comunes: "gluten, lácteos, frutos secos", otros_ingredientes: "harina, avellana, mantequilla", imagen: "../img/tarta-frambuesas.webp" },
    ],
    especiales: [
        { nombre: "Strudel", alergenos_comunes: "gluten, lácteos", otros_ingredientes: "harina, manzana, mantequilla", imagen: "../img/strudel.webp" },
        { nombre: "Rosca choconaranja", alergenos_comunes: "gluten, lácteos", otros_ingredientes: "harina, chocolate, naranja, mantequilla", imagen: "../img/choconaranja.webp" },
        { nombre: "Rosca de chocolate", alergenos_comunes: "gluten, lácteos", otros_ingredientes: "harina, chocolate, mantequilla", imagen: "../img/rosca-chocolate.webp" },
        { nombre: "Trufas", alergenos_comunes: "lácteos", otros_ingredientes: "chocolate amargo, crema para batir", imagen: "../img/trufas.webp" },
        { nombre: "Créme Brûlée", alergenos_comunes: "lácteos, huevo", otros_ingredientes: "crema, azúcar, vainilla", imagen: "../img/creme-brulee.webp" },
        { nombre: "Éclair", alergenos_comunes: "gluten, lácteos", otros_ingredientes: "harina, chocolate, crema pastelera", imagen: "../img/eclair.webp" },
        { nombre: "Gelatina carajillo", alergenos_comunes: "lácteos", otros_ingredientes: "café, licor carajillo, leche condensada", imagen: "../img/carajillo.webp" },
        { nombre: "Gelatina mosaico", alergenos_comunes: "lácteos", otros_ingredientes: "gelatina de colores, leche condensada", imagen: "../img/mosaico.webp" },
        // { nombre: "Gelatina frutos rojos", alergenos_comunes: "lácteos", otros_ingredientes: "gelatina, frutos rojos", imagen: "../img/g-frutos-rojos.jpg" },
        { nombre: "Macarrons", alergenos_comunes: "gluten, frutos secos", otros_ingredientes: "Harina de Almendra, Azúcar, Clara de Huevo", imagen: "../img/macarrons.webp" },
        { nombre: "Mermelada", alergenos_comunes: "sin alérgenos", otros_ingredientes: "Frutas Variadas, Azúcar", imagen: "../img/mermelada.webp" },
        { nombre: "Crema de cacahuate", alergenos_comunes: "frutos secos", otros_ingredientes: "Cacahuate, Azúcar", imagen: "../img/crema-cacahuate.webp" },
        { nombre: "Mil hojas", alergenos_comunes: "gluten, lácteos", otros_ingredientes: "Harina, Crema, Azúcar", imagen: "../img/mil-hojas.webp" },
        { nombre: "Tiramisú", alergenos_comunes: "gluten, lácteos", otros_ingredientes: "Mascarpone, Café, Bizcocho", imagen: "../img/tiramisu.webp" },
        { nombre: "Bombas de chocolate", alergenos_comunes: "gluten, lácteos", otros_ingredientes: "Chocolate, Crema, Azúcar", imagen: "../img/bombas-chocolate.webp" },
        { nombre: "Cheescake", alergenos_comunes: "gluten, lácteos", otros_ingredientes: "Queso Crema, Harina, Azúcar", imagen: "../img/cheesecake.webp" },
        { nombre: "Empanadas", alergenos_comunes: "gluten, lácteos", otros_ingredientes: "Harina, Frutas Variadas, Mantequilla", imagen: "../img/empanadas.webp" },
        { nombre: "Pan de caja", alergenos_comunes: "gluten", otros_ingredientes: "Harina, Levadura, Agua", imagen: "../img/pan-caja.webp" },
],

cupcakes: [
    { nombre: "Cupcake matcha", alergenos_comunes: "gluten, lácteos", otros_ingredientes: "harina, matcha, mantequilla", imagen: "../img/cc-matcha.webp" },
    { nombre: "Cupcake zanahoria", alergenos_comunes: "gluten, lácteos, huevo", otros_ingredientes: "harina, Zanahoria, Mantequilla", imagen: "../img/cc-zanahoria.webp" },
    { nombre: "Cupcake fondant", alergenos_comunes: "gluten, lácteos, huevo", otros_ingredientes: "Harina, Fondant, Mantequilla", imagen: "../img/cc-fondant.webp" },
    // { nombre: "Fruitcake", alergenos_comunes: "gluten, frutos secos, lácteos, huevo", otros_ingredientes: "Azúcar, Canela, Ron (opcional), Jugo de Naranja, Cerezas Negras", imagen: "../img/fruitcake.webp" },
],

panques: [
    { nombre: "Pan de elote", alergenos_comunes: "gluten, lácteos", otros_ingredientes: "Harina, Elote, Mantequilla", imagen: "../img/p-elote.jpg" },
    { nombre: "Panqué de calabaza", alergenos_comunes: "gluten, lácteos", otros_ingredientes: "Harina, Calabaza, Mantequilla", imagen: "../img/p-calabaza.webp" },
    { nombre: "Panqué de plátano", alergenos_comunes: "gluten, lácteos", otros_ingredientes: "Harina, Plátano, Mantequilla", imagen: "../img/p-platano.webp" },
    { nombre: "Panqué de limón amarillo", alergenos_comunes: "gluten, lácteos", otros_ingredientes: "Harina, Limón Amarillo, Mantequilla", imagen: "../img/p-limon.webp" },
]
};
